spring:
  application:
    name:  order-service
server:
  port: 8073
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
    fetch-registry: false
    #禁止注册自己
    register-with-eureka: false